# Generated by Django 5.1.1 on 2024-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_name', models.CharField(max_length=100)),
                ('batch_id', models.CharField(max_length=100)),
                ('login_name', models.CharField(max_length=100)),
                ('param1', models.IntegerField()),
                ('param2', models.IntegerField()),
                ('timer', models.IntegerField()),
                ('state', models.CharField(max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
