# Generated by Django 5.2.4 on 2025-08-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batchdata',
            name='param2',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
